import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDirectory = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = path.join(rootDirectory, 'electron', 'licenseClientConfig.generated.mjs');
const serverUrl = String(process.env.IMH_LICENSE_SERVER_URL || '').trim();
const publicKey = String(process.env.IMH_LICENSE_PUBLIC_KEY || '').trim();

function decodeBase64Url(value) {
  const normalized = value.replace(/-/g, '+').replace(/_/g, '/');
  return Buffer.from(normalized.padEnd(Math.ceil(normalized.length / 4) * 4, '='), 'base64');
}

if (!serverUrl || !publicKey) {
  console.error('IMH_LICENSE_SERVER_URL and IMH_LICENSE_PUBLIC_KEY are required for release packaging.');
  process.exit(1);
}

let parsedUrl;
try {
  parsedUrl = new URL(serverUrl);
} catch {
  console.error('IMH_LICENSE_SERVER_URL must be a valid URL.');
  process.exit(1);
}

if (parsedUrl.protocol !== 'https:' || parsedUrl.hostname.endsWith('.invalid')) {
  console.error('Release license server configuration must use a production HTTPS URL.');
  process.exit(1);
}
if (!/^[A-Za-z0-9_-]+$/.test(publicKey) || decodeBase64Url(publicKey).length !== 32) {
  console.error('IMH_LICENSE_PUBLIC_KEY must be an Ed25519 raw public key encoded as base64url.');
  process.exit(1);
}

const contents = `// Generated by scripts/configureLicenseClient.mjs. Public values only.\nexport const licenseClientConfig = Object.freeze(${JSON.stringify({ serverUrl: parsedUrl.toString().replace(/\/$/, ''), publicKey }, null, 2)});\n`;
await fs.writeFile(outputPath, contents, 'utf8');
console.log('License client public configuration prepared.');
